#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: acamaras <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/02 16:38:26 by acamaras          #+#    #+#              #
#    Updated: 2021/11/02 16:47:05 by acamaras         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = ft_display_file
SCRS = display_file.c
OBJ = display_file.o
all:
	gcc $(SCRS) -o $(NAME) 

clean:
	rm -f $(OBJ)

fclean:
	rm -f $(NAME)

re: fclean all